# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('uid', models.IntegerField(default=0)),
                ('songList', models.CharField(max_length=5000)),
            ],
        ),
    ]
