# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbjjzl', '0002_auto_20160326_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiclist',
            name='title',
        ),
        migrations.AddField(
            model_name='group',
            name='nComment',
            field=models.IntegerField(default=0),
        ),
    ]
