# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbjjzl', '0003_auto_20160410_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='commentList',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
