# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbjjzl', '0005_auto_20160410_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='nComment',
        ),
        migrations.RemoveField(
            model_name='group',
            name='nSong',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='nSong',
        ),
    ]
