# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbjjzl', '0006_auto_20160410_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='grouplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('groupList', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='mygroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('groupList', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='mymusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('songList', models.TextField()),
            ],
        ),
    ]
