# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbjjzl', '0007_grouplist_mygroup_mymusic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mygroup',
        ),
        migrations.DeleteModel(
            name='mymusic',
        ),
        migrations.RemoveField(
            model_name='group',
            name='songList',
        ),
        migrations.AddField(
            model_name='music',
            name='gid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
